#!/bin/sh

/usr/bin/docker buildx build \
  --pull -t gregewing/collectd:latest \
  --platform linux/amd64,linux/arm64,linux/arm/v7 \
  /mnt/RAID/myDockers/gregewing_collectd \
  --push

docker buildx build \
  --pull \
  --platform linux/amd64 \
  --load \
  -t gregewing/collectd:latest .
